### ISSUE TITLE
Reload button in Feedback Manager sometimes freezes ui in loading screen

### ISSUE THREAD

**Issue by markuszm** [stg-tud/kave#17] opened 2015-04-22 20:04 UTC
Sometimes when clicking the "Aktualisieren" button in the Feedback Manager ui the ui can get stuck in the loading screen (see attached picture). I can't really find a reason for this behaviour as it happens sporadically. Sometimes reopening the feedback manager fixes this, but most of the time Visual Studio needs to be restarted.

![image](https://cloud.githubusercontent.com/assets/9436263/7283736/e93fa24a-e938-11e4-8087-a70643f6feb0.png)

**Comment by salsolatragus** [comment] 2015-04-24 06:19
Couldn't reproduce it yet. Working on it.

**Comment by salsolatragus** [comment] 2015-05-06 15:30
I'm still unable to reproduce this in both VS10 and VS13. Since you told me that you couldn't reproduce it either after a restart of VS, I'm going to close this. Please inform me, should the problem reappear!

**Closed by salsolatragus** 2015-05-06 15:30 UTC
Labels: bug
